# coding: utf-8

# flake8: noqa

"""
    Gravatar Public API

    Gravatar's public API endpoints

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.avatars_api import AvatarsApi
from openapi_client.api.profiles_api import ProfilesApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.associated_response import AssociatedResponse
from openapi_client.models.avatar import Avatar
from openapi_client.models.avatar_rating import AvatarRating
from openapi_client.models.crypto_wallet_address import CryptoWalletAddress
from openapi_client.models.error import Error
from openapi_client.models.gallery_image import GalleryImage
from openapi_client.models.interest import Interest
from openapi_client.models.language import Language
from openapi_client.models.link import Link
from openapi_client.models.profile import Profile
from openapi_client.models.profile_contact_info import ProfileContactInfo
from openapi_client.models.profile_payments import ProfilePayments
from openapi_client.models.set_email_avatar_request import SetEmailAvatarRequest
from openapi_client.models.update_avatar_request import UpdateAvatarRequest
from openapi_client.models.verified_account import VerifiedAccount
