# coding: utf-8

"""
    Gravatar Public API

    Gravatar's public API endpoints

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.profiles_api import ProfilesApi


class TestProfilesApi(unittest.TestCase):
    """ProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_associated_email(self) -> None:
        """Test case for associated_email

        Check if the email is associated with the authenticated user
        """
        pass

    def test_get_profile_by_id(self) -> None:
        """Test case for get_profile_by_id

        Get profile by identifier
        """
        pass


if __name__ == '__main__':
    unittest.main()
