# coding: utf-8

"""
    Gravatar Public API

    Gravatar's public API endpoints

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.avatars_api import AvatarsApi


class TestAvatarsApi(unittest.TestCase):
    """AvatarsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AvatarsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_avatar(self) -> None:
        """Test case for delete_avatar

        Delete avatar
        """
        pass

    def test_get_avatars(self) -> None:
        """Test case for get_avatars

        List avatars
        """
        pass

    def test_set_email_avatar(self) -> None:
        """Test case for set_email_avatar

        Set avatar for the hashed email
        """
        pass

    def test_update_avatar(self) -> None:
        """Test case for update_avatar

        Update avatar data
        """
        pass

    def test_upload_avatar(self) -> None:
        """Test case for upload_avatar

        Upload new avatar image
        """
        pass


if __name__ == '__main__':
    unittest.main()
