# coding: utf-8

"""
    Gravatar Public API

    Gravatar's public API endpoints

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.avatar_rating import AvatarRating

class TestAvatarRating(unittest.TestCase):
    """AvatarRating unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvatarRating(self):
        """Test AvatarRating"""
        # inst = AvatarRating()

if __name__ == '__main__':
    unittest.main()
