# coding: utf-8

"""
    Gravatar Public API

    Gravatar's public API endpoints

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_avatar_request import UpdateAvatarRequest

class TestUpdateAvatarRequest(unittest.TestCase):
    """UpdateAvatarRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAvatarRequest:
        """Test UpdateAvatarRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAvatarRequest`
        """
        model = UpdateAvatarRequest()
        if include_optional:
            return UpdateAvatarRequest(
                rating = 'G',
                alt_text = ''
            )
        else:
            return UpdateAvatarRequest(
        )
        """

    def testUpdateAvatarRequest(self):
        """Test UpdateAvatarRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
