# coding: utf-8

"""
    Gravatar Public API

    Gravatar's public API endpoints

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.profile_contact_info import ProfileContactInfo

class TestProfileContactInfo(unittest.TestCase):
    """ProfileContactInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileContactInfo:
        """Test ProfileContactInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileContactInfo`
        """
        model = ProfileContactInfo()
        if include_optional:
            return ProfileContactInfo(
                home_phone = '',
                work_phone = '',
                cell_phone = '',
                email = '',
                contact_form = '',
                calendar = ''
            )
        else:
            return ProfileContactInfo(
        )
        """

    def testProfileContactInfo(self):
        """Test ProfileContactInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
