# coding: utf-8

"""
    Gravatar Public API

    Gravatar's public API endpoints

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.verified_account import VerifiedAccount

class TestVerifiedAccount(unittest.TestCase):
    """VerifiedAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifiedAccount:
        """Test VerifiedAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifiedAccount`
        """
        model = VerifiedAccount()
        if include_optional:
            return VerifiedAccount(
                service_type = '',
                service_label = '',
                service_icon = '',
                url = '',
                is_hidden = True
            )
        else:
            return VerifiedAccount(
                service_type = '',
                service_label = '',
                service_icon = '',
                url = '',
                is_hidden = True,
        )
        """

    def testVerifiedAccount(self):
        """Test VerifiedAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
